---

dist: bionic

matrix:
  fast_finish: true
  include:
    - os: linux
      services: docker
      language: python
      python: "3.8"
      env:
        - ANSIBLE_VERSION="2.8"
        - MOLECULE_SCENARIO="default"
    - os: linux
      services: docker
      language: python
      python: "3.8"
      env:
        - ANSIBLE_VERSION="2.8"
        - MOLECULE_SCENARIO="default"
        - MOLECULE_DISTRIBUTION="ubuntu18"


install:
  - pip3 install -U pip
  - pip install ansible=="$ANSIBLE_VER.*" testinfra molecule docker
script:
  - python --version
  - molecule --version
  - ansible --version
  - molecule test -s $MOLECULE_SCENARIO

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
