---

dist: bionic
language: python
python: 3.8

matrix:
  fast_finish: true
  include:
    - os: linux
      env:
        - ANSIBLE_VERSION="stable-2.9"
        - MOLECULE_SCENARIO="default"

before_install:
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common podman
  - sudo mkdir -p /etc/containers
  - sudo sh -c 'echo -e "[registries.search]\nregistries = [\"docker.io\"]" > /etc/containers/registries.conf'

install:
  - pip3 install -U pip
  - |
    ansible_dir="$(mktemp -d 2> /dev/null || mktemp -d -t 'mytmpdir')"
    git clone -b "\'${ANSIBLE_VERSION}\'" \
      --single-branch \
      --depth 1 \
      https://github.com/ansible/ansible.git "${ansible-dir}" > /dev/null 2>&1
    python3 "${ansible_dir}/setup.sh" install
  - pip3 install testinfra "molecule[podman]"
script:
  - python --version
  - molecule --version
  - ansible --version
  - molecule test -s $TEST_SCENARIO

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/