# Download rustup
---
- name: Set distro-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml

- name: Install rustup system requirements
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ rustup_packages }}"
  become: true
  become_user: root

- name: Install RustUp
  ansible.builtin.shell: |
    set -o pipefail
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  args:
    creates: "{{ rustup_user_home }}/{{ rustup_cargo_home_suffix }}/bin/rustup"
    executable: /bin/bash
  environment:
    TMPDIR: '{{ temp_install_dir.path }}'
    RUSTUP_HOME: "{{ rustup_user_home }}/{{ rustup_home_suffix }}"
    CARGO_HOME: "{{ rustup_user_home }}/{{ rustup_cargo_home_suffix }}"
