---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: '.direnv/'
platforms:
  - name: rustup_install_${MOLECULE_DISTRIBUTION:-fedora30}
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-fedora30}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: yes
provisioner:
  name: ansible
  options:
    vvv: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: ../shared/tests
  env:
    MOLECULE_SCENARIO: "default"
  options:
    verbose: true
  lint:
    name: flake8
